# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/extract_keywords',
                'doc_host': 'https://anuroop18.github.io',
                'git_url': 'https://github.com/anuroop18/extract_keywords',
                'lib_path': 'extract_keywords'},
  'syms': { 'extract_keywords.core': { 'extract_keywords.core.generate_keywords': ( 'core.html#generate_keywords',
                                                                                    'extract_keywords/core.py'),
                                       'extract_keywords.core.is_word_in_range': ('core.html#is_word_in_range', 'extract_keywords/core.py'),
                                       'extract_keywords.core.read_in_text': ('core.html#read_in_text', 'extract_keywords/core.py'),
                                       'extract_keywords.core.remove_singular_words': ( 'core.html#remove_singular_words',
                                                                                        'extract_keywords/core.py')}}}
